wandb_version: 1

project_name:
  desc: null
  value: demo_setup
experiment_name:
  desc: null
  value: experiment-0
learning-rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700504386.013361
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.0
      8:
      - 4
      - 5
      13: darwin-arm64
